Elibrary/urls.py
from django.contrib import admin
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include


urlpatterns = [
    path('', views.index, name='index'),
    path('app/', include('app.urls')),
    path("admin/", admin.site.urls),
    path('accounts/', include('registration.backends.simple.urls')),


] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/urls.py
from django.urls import path
from app import views

app_name = 'elib'

urlpatterns = [
    path('', views.index, name='index'),

    path('borrow_history/', views.borrow_history, name='borrow_history'),
    path('contactus/', views.contact_us, name='contact_us'),
    path('search/', views.search, name='search'),

    # book details
    path('book_details/<int:book_id>/', views.book_details, name='book_details'),
    path('borrow_book/', views.borrow_book, name='borrow_book'),

    # personal page
    path('personal_page/', views.personal_page, name='personal_page'),

    # recommends
    path('recommends/', views.recommends, name='recommends'),

]

app/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

class Book(models.Model):
    bookid = models.IntegerField(primary_key=True, null=False)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    booknum = models.IntegerField(null=False)  # remain number
    description = models.TextField()
    bookpic = models.TextField(default='undefined')
    bookcategory = models.TextField(default='undefined')

    def __str__(self):
        return self.title

    class Meta:
        db_table = 'Book'


# the borrowing history
class Record(models.Model):
    rentno = models.IntegerField(primary_key=True, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrow_date = models.DateTimeField(auto_now_add=True)
    return_date = models.DateTimeField(null=True, blank=True)
    rent_deadline = models.DateTimeField(null=True, blank=True)
    rent_sts = models.BooleanField(default=True)

    class Meta:
        db_table = 'Record'

app/forms.py
from django import forms
from app.models import Book


class BorrowBookForm(forms.Form):
    book_id = forms.IntegerField()

    def borrow_book(self):
        book_id = self.cleaned_data['book_id']
        book = Book.objects.get(pk=book_id)
        book.book_num -= 1
        book.save()

app/views.py
from datetime import timedelta, datetime
from django.contrib.auth.decorators import login_required
from django.db.models import Q, Min
from django.shortcuts import render
from django.urls import reverse
from app.models import Book, Record
from django.contrib import messages
from django.http import HttpResponseRedirect


def index(request):
    #show 3 new books by largest bookid
    new_books = Book.objects.order_by('-bookid')[:3]

    #each catagory get the first id's book
    categories = Book.objects.values('bookcategory').annotate(bookid_min=Min('bookid'))
    category_books = [Book.objects.get(bookid=category['bookid_min']) for category in categories]

    data = {
        'new_books': new_books,
        'category_books':category_books,
    }

    return render(request, 'app/index.html', context=data)


@login_required
def borrow_history(request):
    if request.method == 'GET':
        #user_id = request.GET.get('user_id')  # the tag's 'name' in html
        user_id = request.user.id
        #print(user_id)
        records = Record.objects.filter(user=user_id)
        data = {
            'records': [
                {
                    'username': record.user.username,
                    'book_id': record.book.bookid,
                    'book_title': record.book.title,
                    'borrow_date': record.borrow_date.strftime('%Y-%m-%d %H:%M:%S'),
                    'return_date': record.return_date.strftime('%Y-%m-%d %H:%M:%S') if record.return_date else ''
                } for record in records
            ]
        }
        #print(data)
        return render(request, 'app/borrow_history.html', context=data)


def search(request):
    # the html file's tag name
    if request.method == 'POST':
        query = request.POST.get('search')
        #print(query)
        if query:
            # search in the db with title or author
            books = Book.objects.filter(Q(title__icontains=query) | Q(author__icontains=query))
            #print(books)
        else:
            #print('search no book')
            books = Book.objects.none()  # empty QuerySet

    return render(request, 'app/book_search.html', {'books': books, 'query': query})



def contact_us(request):
    return render(request, 'app/contactus.html')


def book_details(request, book_id):

    book =Book.objects.get(bookid=book_id)

    # find 3 related books
    related_books = Book.objects.filter(bookcategory=book.bookcategory).exclude(bookid=book_id)[:3]
    #print(book)
    data = {
        'book': book,
        'related_books': related_books,
    }
    #print(data)
    return render(request, 'app/book_details.html', context=data)


@login_required
def borrow_book(request):
    #print('borrow_book user', request.user)
    #print('user id:', request.user.id)
    if request.method == 'POST':
        book_id = request.POST.get('book_id')
        #print('bookid:',book_id)
        book = Book.objects.get(bookid=book_id)
        #print(book,book.booknum)

        if book.booknum == 0:
            messages.error(request, "This book is currently out of stock.")
            return HttpResponseRedirect(reverse('elib:book_details', args=[book_id]))

        else:
            # Add borrow_record
            rent_deadline = datetime.now() + timedelta(days=30)
            record = Record(user_id=request.user.id, book_id=book.bookid, rent_deadline=rent_deadline)
            record.save()

            # Only reduce the booknum and save the book after the record is saved
            book.booknum -= 1
            book.save()

            messages.success(request, "Book borrowed successfully!")
            return HttpResponseRedirect(reverse('elib:book_details', args=[book_id]))



@login_required
def personal_page(request):
    uid = request.user.id
    records = Record.objects.filter(user=uid)

    data = {
        'records': [
            {
                'book_pic': record.book.bookpic,
                'username': record.user.username,
                'user_id': record.user,
                'book_id': record.book.bookid,
                'book_name': record.book.title,
                'borrow_date': record.borrow_date.strftime('%Y-%m-%d %H:%M:%S'),
                'deadline': record.rent_deadline.strftime('%Y-%m-%d %H:%M:%S'),
            } for record in records
        ],
        'username': request.user.username,
        'uid': uid,
        'date_joined': request.user.date_joined,
    }

    #print(data)
    return render(request, 'app/personalPage.html', context=data)


def recommends(request):
    if request.method == 'GET':
        category = request.GET.get('category')
        if category:
            books = Book.objects.filter(bookcategory=category)
            data = {'books': books}

        return render(request, 'app/recommends.html', context=data)

app/templates/book_details.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Book Details Page</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %} ">
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="{% static 'js/bookDetails.js' %}"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
</head>
<body>
<div class="header">
    <div class="rectangle-top">
        <p>E-library</p>
    </div>

    <div class="container3">
        <div>
            <b class="paragraph-1-copy-8">@E-library </b>
        </div>

        <!-- Search -->
        <div class="search-container">
            <form method="get">
                <input type="text" placeholder="Search for..." name="book_title">
                <button type="submit"><i class="fa fa-search fa-2x" aria-hidden="true"></i></button>
            </form>
        </div>

        <div class="top-right">

            <!-- Heart -->
            <a class=" right-icon" href="url">
                <i class="fa fa-heart-o fa-lg" aria-hidden="true"></i>
            </a>

            <!-- User information -->
            <a class="right-icon " href="url">
                <i class="fa fa-user-o fa-lg" aria-hidden="true"></i>
            </a>
            <!-- Login, Register -->
            <a class="login-register" href="url">Login</a>
            <b class="login-register">/</b>
            <a class="login-register" href="url">Register</a>

        </div>
    </div>
    {% if request.method == 'GET'%}
    {% for book in books %}
    <div class="container2">
        <div class="link-bar1-style">
            <a class="link-bar-1" href="url"> Literature </a>
            <a class="link-bar-1" href="url"> Fiction </a>
            <a class="link-bar-1" href="url"> History </a>
            <a class="link-bar-1" href="url"> Art </a>
            <a class="link-bar-1" href="url"> Business</a>
            <a class="link-bar-1" href="url"> Comics </a>
            <a class="link-bar-1" href="url"> Science </a>
            <a class="link-bar-1" href="url"> Social </a>
        </div>

        <div class="button-contact-style">
            <button class="button-contact">Contact Us</button>

        </div>
    </div>

</div>
<hr>

<div class="main">
    <div class="link-bar2-style">
        <a class="link-bar-2">allbooks > category > select book</a>
    </div>

    <!--book title author rate description-->
    <div class="bookinfo-top">

        <!--bookcover img -->
        <div class="image-bookcover">
            <img src="/static/img/luffy.png" alt="book cover">
        </div>
        <!-- booktitle -->
        <div>

            <p1 class="bookinfo-title">{{ book.book_title }}</p1>
            <!-- author -->
            <p class="bookinfo-author"> {{ book.book_author }}</p>

            <div class="bookinfo-rate">

                <!-- Rate -->
                <p class="bookinfo-star"> Rate It</p>
                <div class="rating">
                    <input type="radio" id="star5" name="rating" value="5"/>
                    <label for="star5" title="5星"></label>
                    <input type="radio" id="star4" name="rating" value="4"/>
                    <label for="star4" title="4星"></label>
                    <input type="radio" id="star3" name="rating" value="3"/>
                    <label for="star3" title="3星"></label>
                    <input type="radio" id="star2" name="rating" value="2"/>
                    <label for="star2" title="2星"></label>
                    <input type="radio" id="star1" name="rating" value="1"/>
                    <label for="star1" title="1星"></label>
                </div>

                <!-- Available Dot -->
                {% if book.book_num > 0 %}
                <div class="book-status">
                    <div class="dot available"></div>
                    <div class="text">Available</div>
                </div>
                {% else %}
                <div class="book-status">
                    <div class="dot unavailable"></div>
                    <div class="text">Unavailable</div>
                </div>
                {% endif %}

                <!-- heart -->
                <div class="heart">
                    <i class="fa fa-heart-o fa-2x" aria-hidden="true"></i>
                </div>


                <!-- Borrow Now btn & Review -->
                <div>
                    <form id="borrow-form" method="POST" action="{% url 'borrow_book' %}">
                        {% csrf_token %}
                        <input type="hidden" name="book_id" value="{{ book.book_id }}">
                        <button class="borrowbutton" id="borrow-now-btn" data-book-id="{{ book.book_id }}">Borrow Now
                        </button>

                    </form>

                </div>

                <div class=" write-review ">
                    <a href="review.html" class="review-link" href="url">
                        <i class="fa fa-comment-o fa-3x"></i>
                        Write a Review
                    </a>
                </div>


            </div>
        </div>


    </div>
    <div id="container">

        <!--bottom introduction -->
        <!--    <div class="bookintro">-->
        <div class="text-container">
            <p class="text">{{ book.book_description }}</p>
            <button class="read-more">Read More</button>
        </div>


        <!--    </div>-->

        <hr>

        <!--    authordetails reviews..-->
        <!--    <div class="author-detail">-->
        <!--        <p class="text-author-details">Author Details</p>-->

        <!--    </div>-->
        <div class="author-info">
            <div class="author-header">
                <h3>Author Details</h3>
                <span class="toggle-arrow">&#x25B6;</span>
            </div>
            <div class="author-details">
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultricies ligula in ex consequat,
                    vel
                    interdum nibh pulvinar. Nulla eget maximus tortor. Donec faucibus odio in sapien convallis, id
                    interdum
                    ipsum lobortis. Sed blandit eget mi ut tempus. Sed porta aliquet dui, in efficitur purus vehicula
                    sit
                    amet. Fusce et nibh sed lectus pellentesque varius. Pellentesque pharetra auctor ex at venenatis.
                    Sed
                    non metus non sem tincidunt lobortis sed quis tellus.</p>
            </div>
        </div>


        <hr>
        <div class="reviews-info">
            <div class="reviews-header">
                <h3>Reviews</h3>
                <span class="toggle-arrow">&#x25B6;</span>
            </div>
            <div class="reviews-details">
                <!--                *****************************-->
                <div class="comment">
                    <div class="comment-header">
                        <span class="comment-author">John Doe</span>
                        <span class="comment-date">2023-03-20</span>
                    </div>
                    <div class="comment-body">
                        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu nisl sit amet urna interdum
                        ullamcorper. Sed non lectus vel dolor eleifend tempus. Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit. Donec eu nisl sit amet urna interdum
                        ullamcorper. Sed non lectus vel dolor eleifend tempus. Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit. Donec eu nisl sit amet urna interdum
                        ullamcorper. Sed non lectus vel dolor eleifend tempus. Lorem ipsum dolor sit amet, consectetur
                        adipiscing elit. Donec eu nisl sit amet urna interdum
                        ullamcorper. Sed non lectus vel dolor eleifend tempus.
                    </div>
                    <div class="comment-footer">
                        <a href="#" class="comment-toggle">Show More</a>
                    </div>
                </div>

                <!--                *****************************-->
            </div>

        </div>


    </div>


    {% endfor %}
    {% endif %}

    <hr>
    <div class="related"> Related Books</div>
    <div class="related-images">
        <div class="images">
            <img src="/static/img/luffy.png" alt="Image 1">
            <img src="/static/img/luffy.png" alt="Image 2">
            <img src="/static/img/luffy.png" alt="Image 3">
            <img src="/static/img/luffy.png" alt="Image 4">
            <img src="/static/img/luffy.png" alt="Image 5">
        </div>
        <button class="arrow"></button>

    </div>
</div>


</div>
</body>
</html>

templates/app/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
	<title>
        {% block title %}{% endblock %}
    </title>

	{% block link %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1/css/bootstrap.css' %}">
         <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
        <!-- other links-->
	{% endblock %}
</head>

<body>
    <header>
		E-library
    </header>

    <div class="page_top">
        <a href="{% url 'elib:index' %}" ><label class="copyright">@E-Library</label></a>

        {% if user.is_authenticated %}
            <!--user is login, redirect to the personal page-->
            <a href="{% url 'elib:personal_page' %}">
                <img src="{% static 'images/user.jpg' %}" alt="Picture of User" id="user-icon"/>
            </a>
            <a href="{% url 'auth_logout' %}?next={% url 'elib:index' %}" id="logout" class="logout">Logout</a>

        {% else %}
            <!--user not login, redirect to login page-->
            <a href="{% url 'auth_login' %}">
                <img src="{% static 'images/user.jpg' %}" alt="Picture of User" id="user-icon"/>
            </a>
            <a href="{% url 'auth_login' %}" id="logout" class="logout">Login</a>
        {% endif %}

        <a href="{% url 'elib:contact_us' %}" id="contact-button">Contact Us</a>

        <form id="search-form" action="{% url 'elib:search' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <input type="text" id="search" name="search" placeholder="Search book...">
            <button type="submit" id="search-button"><i class="fa fa-search fa-2x " aria-hidden="true"></i></button>
        </form>
    </div>

    <div class="recommends ">
        <ul class = "nav nav-tabs menu">
            <li><a href="{% url 'elib:recommends' %}?category=literature">Literature</a></li>
            <li><a href="{% url 'elib:recommends' %}?category=fiction">Fiction</a></li>
            <li><a href="{% url 'elib:recommends' %}?category=history">History</a></li>
            <li><a href="{% url 'elib:recommends' %}?category=business">Business</a></li>
            <li><a href="{% url 'elib:recommends' %}?category=comics">Comics</a></li>
            <li><a href="{% url 'elib:recommends' %}?category=social">Social</a></li>
        </ul>
    </div>

    {% block content %}
        <!--other page's content-->
    {% endblock %}
    
</body>
</html>

templates/app/book_details.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Book Details Page{% endblock %}

{% block link %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/book_detail.css' %} ">
    <script src="{% static 'js/jquery-3.6.4.min.js' %}"></script>
    <script src="{% static 'js/bookDetails.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

{% endblock %}


{% block content %}

    <div class="main">

        <!--book title author rate description-->
        <div class="bookinfo-top">

            <!--bookcover img -->
            <div class="container">
                <div class="image-bookcover">
                    <img src="{{ book.bookpic }}" alt="book cover" id="bookcover">
                </div>
            </div>

            <!-- booktitle -->
            <div>
                <p1 class="bookinfo-title">{{ book.title }}</p1>
                <!-- author -->
                <p class="bookinfo-author"> {{ book.author }}</p>

                <div class="bookinfo-rate">

                    <!-- Rate -->
                    <p class="bookinfo-star">Rate It</p>
                    <div class="rating">
                        <input type="radio" id="star5" name="rating" value="5"/>
                        <label for="star5" title="5星"></label>
                        <input type="radio" id="star4" name="rating" value="4"/>
                        <label for="star4" title="4星"></label>
                        <input type="radio" id="star3" name="rating" value="3"/>
                        <label for="star3" title="3星"></label>
                        <input type="radio" id="star2" name="rating" value="2"/>
                        <label for="star2" title="2星"></label>
                        <input type="radio" id="star1" name="rating" value="1"/>
                        <label for="star1" title="1星"></label>
                    </div>

                    <!-- Available Dot -->
                    {% if book.booknum > 0 %}
                        <div class="book-status">
                            <div class="dot available"></div>
                            <div class="text">Available</div>
                        </div>
                    {% else %}
                        <div class="book-status">
                            <div class="dot unavailable"></div>
                            <div class="text">Unavailable</div>
                        </div>
                    {% endif %}

                    <!-- Display messages -->
                    {% if messages %}
                        <div id="message-box" class="message-box">
                            {% for message in messages %}
                                <div{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                                    <h3>{{ message }}</h3>
                                </div>
                            {% endfor %}
                        </div>
                    {% endif %}

                    <!-- Borrow Now btn & Review -->
                    <div>
                        <form id="borrow-form" method="POST" action="{% url 'elib:borrow_book' %}">
                            {% csrf_token %}
                            <input type="hidden" name="book_id" id="book-id" value="{{ book.bookid }}">
                            <button class="borrowbutton" id="borrow-now-btn" data-book-id="{{ book.bookid }}">Borrow
                                Now
                            </button>
                        </form>
                    </div>

{#                    <div class=" write-review ">#}
{#                        <a href=" " class="review-link" href="url">#}
{#                            <i class="fa fa-comment-o fa-3x"></i>#}
{#                            Write a Review#}
{#                        </a>#}
{#                    </div>#}


                </div>
            </div>
        </div>

        <div id="container">

            <!--bottom introduction -->
            <!--    <div class="bookintro">-->
            <div class="text-container">
                <p class="text">{{ book.description }}</p>
                <button class="read-more">Read More</button>
            </div>

            <hr>

            <div class="author-info">
                <div class="author-header">
                    <h3>Author Details</h3>
                    <span class="toggle-arrow">&#x25B6;</span>
                </div>
                <div class="author-details">
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam ultricies ligula in ex
                        consequat,
                        vel
                        interdum nibh pulvinar. Nulla eget maximus tortor. Donec faucibus odio in sapien convallis, id
                        interdum
                        ipsum lobortis. Sed blandit eget mi ut tempus. Sed porta aliquet dui, in efficitur purus
                        vehicula
                        sit
                        amet. Fusce et nibh sed lectus pellentesque varius. Pellentesque pharetra auctor ex at
                        venenatis.
                        Sed
                        non metus non sem tincidunt lobortis sed quis tellus.</p>
                </div>
            </div>


            <hr>
            <div class="reviews-info">
                <div class="reviews-header">
                    <h3>Reviews</h3>
                    <span class="toggle-arrow">&#x25B6;</span>
                </div>
                <div class="reviews-details">
                    <div class="comment">
                        <div class="comment-header">
                            <span class="comment-author">John Doe</span>
                            <span class="comment-date">2023-03-20</span>
                        </div>
                        <div class="comment-body">
                            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec eu nisl sit amet urna
                            interdum
                            ullamcorper. Sed non lectus vel dolor eleifend tempus. Lorem ipsum dolor sit amet,
                            consectetur
                            adipiscing elit. Donec eu nisl sit amet urna interdum
                            ullamcorper. Sed non lectus vel dolor eleifend tempus. Lorem ipsum dolor sit amet,
                            consectetur
                            adipiscing elit. Donec eu nisl sit amet urna interdum
                            ullamcorper. Sed non lectus vel dolor eleifend tempus. Lorem ipsum dolor sit amet,
                            consectetur
                            adipiscing elit. Donec eu nisl sit amet urna interdum
                            ullamcorper. Sed non lectus vel dolor eleifend tempus.
                        </div>
                        <div class="comment-footer">
                            <a href="#" class="comment-toggle">Show More</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
        <hr>

        <h3> Related Books</h3>
        <div class="new">
            <div class="container">
                <div class="row">
                    {% for related_book in related_books %}
                        <div class="col-sm-6 col-md-4">
                            <div class="thumbnail">
                                <a href="{% url 'elib:book_details' related_book.bookid %}">
                                    <img src="{{ related_book.bookpic }}" alt="related book pic 1">
                                    <h4>{{ related_book.title }}</h4>
                                    <p>{{ related_book.author }}</p>
                                    {% if related_book.booknum > 0 %}
                                        <p class="text">Available</p>
                                    {% else %}
                                        <p class="text">Unavailable</p>
                                    {% endif %}
                                </a>

                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>



{% endblock %}

templates/app/contactus.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Contact Us</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/contactus.css' %}">
</head>

<body>
	<header>
		E-library
	</header>

	<main>
		<h1>Contact Us</h1>
		<div class="contact-info">
			<h2>Contact Information</h2>
			<ul>
				<li>Lujing Cai, 2790843C@student.gla.ac.uk</li>
                <li>Zhixian Qi, 2815122Q@student.gla.ac.uk</li>
                <li>Zhiheng Zhang, 2727457Z@student.gla.ac.uk</li>
                <li>Yuxi Wang, 2772785W@student.gla.ac.uk</li>
                <li>Bingcen Luo, 2709712L@student.gla.ac.uk</li>
			</ul>
		</div>
		<form class="contact-form" action="{% url 'elib:contact_us' %}" method="post">
			{% csrf_token %}
			<label for="name">Name:</label>
			<input type="text" id="name" name="name" required>
			<label for="email">Email:</label>
			<input type="email" id="email" name="email" required>
			<label for="subject">Subject:</label>
			<input type="text" id="subject" name="subject" required>
			<label for="message">Message:</label>
			<textarea id="message" name="message" required></textarea>
			<button type="submit">Send</button>
		</form>
	</main>

    <div id="success-message" class="hidden">
        <p>Thank you for contacting us!</p>
    </div>

    <!--JS-->
    <script src="{% static 'js/contactus.js' %}"></script>

</body>
</html>

templates/app/personalPage.html
{% extends 'app/base.html' %}
{% load static %}

{% block title %}Personal Page{% endblock %}

{% block link %}
    {{ block.super }}
     <link rel="stylesheet" type="text/css" href="{% static 'css/personalPage.css' %}">
{% endblock %}

{% block content %}
        <div class="container">
            <div class ="row">
                    <div class="col-md-3">
                        <img src ="{% static 'images/luffy.png' %}">
                    </div>

                    <div class="col-md-3">
                        <h3>Username: {{username}}</h3>
                        <h3>ID: {{uid}}</h3>
                    </div>

                    <div class="col-md-3 col-md-offset-3">
                        <h3>Date of creation: {{date_joined}}</h3>
                    </div>

            </div>
        </div>

    <hr />

    <div class="container">
            <a href="{% url 'elib:borrow_history' %}">
                <h1>Books being borrowed</h1>
            </a>
                {% for item in records %}
                    <div class = "col-sm-6 col-md-4">
                        <div class = "thumbnail">
                            <img src ="{{ item.book_pic }}" alt="{{ item.book_name }}">
                            <h4><a href="{% url 'elib:book_details' book_id=item.book_id %}">{{item.book_name }}</a></h4>
                            <p>Rent Time:{{item.borrow_date}}</p>
                            <p>Deadline:{{item.deadline}}</p>
                        </div>
                    </div>
                {% endfor %}
    </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
	<title>
        {% block title %}{% endblock %}
    </title>

	{% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
        <!-- other page's css link-->
	{% endblock %}
</head>

<body>
    <header>
		E-library
    </header>

    <div class="page_top">
        <label class="copyright">@E-Library</label>

        <a href="">
                <img src="{% static 'images/user.jpg' %}" alt="Picture of User" id="user-icon"/>
        </a>

        <a href="{% url 'elib:contact_us' %}" id="contact-button">Contact Us</a>

        <form id="search-form" action="{% url 'elib:book_search' %}" method="post" autocomplete="off">
            {% csrf_token %}
            <input type="text" id="search" name="search" placeholder="Search book...">
            <button type="submit" id="search-button">Search</button>
        </form>
    </div>

    {% block content %}
        <!--other page's content-->
    {% endblock %}
    
</body>
</html>